Repository quantcdn/drupal, pull requests merged in 2022-11, with the labels that each got.

#69 Drupal 10 compatibility
  .github/workflows/ci.yml
  README.md
  modules/quant_api/quant_api.info.yml
  modules/quant_api/src/Client/QuantClient.php
  modules/quant_api/src/EventSubscriber/QuantApi.php
  modules/quant_api/tests/src/Unit/QuantClientTest.php
  modules/quant_cron/quant_cron.info.yml
  modules/quant_cron/quant_cron.module
  modules/quant_cron/src/Form/CronSettingsForm.php
  modules/quant_purger/quant_purger.info.yml
  modules/quant_search/quant_search.info.yml
  modules/quant_search/quant_search.module
  modules/quant_search/src/Form/QuantSearchPageForm.php
  modules/quant_search/src/Form/SearchIndexForm.php
  modules/quant_search/src/Routing/QuantSearchRoutes.php
  modules/quant_sitemap/quant_sitemap.info.yml
  modules/quant_sitemap/tests/src/Unit/CollectionSubscriberTest.php
  modules/quant_tome/quant_tome.info.yml
  modules/quant_webform/quant_webform.info.yml
  quant.info.yml
  src/Commands/QuantDrushCommands.php
  src/Event/ConfigFormEventBase.php
  src/Event/NodeInsertEvent.php
  src/Event/QuantEvent.php
  src/Event/QuantFileEvent.php
  src/Event/QuantRedirectEvent.php
  src/EventSubscriber/CollectionSubscriber.php
  src/EventSubscriber/TokenAccessSubscriber.php
  src/Form/SeedForm.php
  src/Plugin/QueueItem/FileItem.php
  src/Plugin/QueueItem/RedirectItem.php
  src/Plugin/QueueItem/RouteItem.php
  src/Seed.php
Labels: enhancement, Drupal 8 / 9 / 10

#71 [ISSUE-70] Fix default Webserver URL value.
  .gitignore
  src/Form/ConfigForm.php
Labels: bug, Drupal 8 / 9 / 10, needs review

#74 [ISSUE-72] Check if views display is enabled and don't add default.
  src/EventSubscriber/CollectionSubscriber.php
Labels: bug, Drupal 8 / 9 / 10, needs review

#76 [ISSUE-75] Add facets validation code.
  modules/quant_search/src/Form/QuantSearchPageForm.php
Labels: bug, Drupal 8 / 9 / 10, needs review

#73 Search autocomplete
  modules/quant_api/src/Form/SettingsForm.php
  modules/quant_search/css/quant_search.autocomplete.css
  modules/quant_search/js/quant-autocomplete.js
  modules/quant_search/quant_search.libraries.yml
  modules/quant_search/quant_search.module
  modules/quant_search/src/Controller/Search.php
  modules/quant_search/src/Plugin/Block/AutocompleteBlock.php
  modules/quant_search/templates/autocomplete-block.html.twig
  modules/quant_tome/src/QuantTomeBatch.php
  src/Plugin/QueueItem/RouteItem.php
Labels: enhancement, Drupal 8 / 9 / 10, needs review
