Repository quantcdn/drupal, pull requests merged in 2022-12, with the labels that each got.

#79 Removed core key, cleaned up tome info yml.
  .github/workflows/ci.yml
  modules/quant_api/quant_api.info.yml
  modules/quant_api/src/Client/QuantClient.php
  modules/quant_cron/quant_cron.module
  modules/quant_tome/quant_tome.info.yml
Labels: bug, Drupal 8 / 9 / 10

#78 [ISSUE-77] Add token module to dependencies.
  .github/workflows/ci.yml
  modules/quant_search/quant_search.info.yml
  modules/quant_search/quant_search.install
  modules/quant_search/src/Form/SearchEntitiesForm.php
Labels: bug, Drupal 8 / 9 / 10, needs review

#90 [ISSUE-89] Update search button CSS to use transparent background.
  modules/quant_search/css/quant_search.algolia.css
  modules/quant_search/css/quant_search.autocomplete.css
Labels: enhancement, Drupal 8 / 9 / 10, needs review

#88 [ISSUE-87] Change deprecated code for Drupal 10 compatibility.
  modules/quant_tome/src/EventSubscriber/RedirectSubscriber.php
Labels: enhancement, Drupal 8 / 9 / 10, needs review
