Repository quantcdn/drupal, pull requests merged in 2023-07, with the labels that each got.

#179 Add option to use GET vs POST for seeding.
  modules/quant_api/quant_api.admin.inc
  modules/quant_api/quant_api.install
  quant.module
Labels: enhancement, Drupal 7, needs review

#182 7.x: Minor bugfixes to admin forms
  modules/quant_api/quant_api.admin.inc
  quant.admin.inc
  quant.module
Labels: bug, Drupal 7

#177 Update User-Agent to correct domain.
  modules/quant_api/quant_api.module
  modules/quant_redirect/quant_redirect.module
Labels: bug, Drupal 7, needs review

#183 Handle circular dependency between quant and quant_api.
  modules/quant_api/quant_api.info
  modules/quant_api/quant_api.module
Labels: bug, Drupal 7, needs review

#175 Add basic validation for Webserver URL field.
  modules/quant_api/quant_api.module
  quant.admin.inc
  quant.module
Labels: Drupal 7, task

#180 Created new seed log and skip option.
  modules/quant_api/quant_api.admin.inc
  modules/quant_api/quant_api.module
  modules/quant_cron/quant_cron.admin.inc
  modules/quant_file/quant_file.module
  modules/quant_redirect/quant_redirect.module
  modules/quant_sitemap/quant_sitemap.module
  quant.admin.inc
  quant.drush.inc
  quant.info
  quant.install
  quant.module
  views/quant.views.inc
  views/quant.views_default.inc
  views/quant_log.view
  views/views_handler_field_quant_static_url.inc
Labels: enhancement, Drupal 7, needs review, in progress

#178 Change quant_file dependency from file to file_entity.
  modules/quant_file/quant_file.info
Labels: bug, Drupal 7, needs review

#184 Default quant_seed_get to TRUE and add update hook.
  modules/quant_api/quant_api.install
  quant.admin.inc
  quant.install
  quant.module
Labels: Drupal 7, needs review, task

#185 Minor tweak to url handling for quant_log.
  quant.module
Labels: Drupal 7, needs review, task

#155 Feat: Add defaults and verify exclusion handling.
  modules/quant_purger/config/install/quant_purger.settings.yml
  modules/quant_purger/quant_purger.install
  modules/quant_purger/quant_purger.links.task.yml
  modules/quant_purger/quant_purger.routing.yml
  modules/quant_purger/src/Controller/QuantPurgerController.php
  modules/quant_purger/src/Form/ConfigurationForm.php
  modules/quant_purger/src/Plugin/Purge/Queuer/QuantPurger.php
  modules/quant_purger/src/StackMiddleware/TraitUrlRegistrar.php
  modules/quant_purger/src/StackMiddleware/UrlRegistrar.php
  modules/quant_purger/src/TrafficRegistry.php
Labels: enhancement, Drupal 8 / 9 / 10

#94 Bail out of run-queue if another run is in progress.
  src/Commands/QuantDrushCommands.php
Labels: enhancement, Drupal 8 / 9 / 10, needs work
