Repository quantcdn/drupal, pull requests merged in 2023-03, with the labels that each got.

#147 [ISSUE-146] Handle exception to prevent warnings.
  modules/quant_api/src/EventSubscriber/QuantApi.php
Labels: bug, Drupal 8 / 9 / 10, needs review

#145 [ISSUE-144] Add module configure links. Credit @Sahana_N on drupal.org.
  modules/quant_api/quant_api.info.yml
  modules/quant_cron/quant_cron.info.yml
  modules/quant_search/quant_search.info.yml
  quant.info.yml
Labels: Drupal 8 / 9 / 10, needs review, UX, task

#148 [ISSUE-99] Handle multilingual manual redirects.
  modules/quant_api/src/EventSubscriber/QuantApi.php
  src/EventSubscriber/CollectionSubscriber.php
  src/Seed.php
Labels: bug, Drupal 8 / 9 / 10, needs review

#143 Add Xpath Follow Links functionality (D7)
  quant.admin.inc
  quant.install
  quant.module
Labels: enhancement, Drupal 7
