Repository quantcdn/drupal, pull requests merged in 2023-06, with the labels that each got.

#151 Feat: Queue uniqueness
  quant.admin.inc
  quant.install
  quant.module
  quant_queue_class.inc
Labels: enhancement, Drupal 7, needs review

#156 Update UI to use organization instead of customer.
  modules/quant_api/quant_api.admin.inc
  modules/quant_api/quant_api.module
  quant.drush.inc
Labels: Drupal 7, UX

#159 Hardcode the CI mariadb version to get around failure.
  .github/workflows/ci.yml
Labels: bug, Drupal 8 / 9 / 10, DX

#158 Improve help text and error handling text for API form.
  modules/quant_api/quant_api.admin.inc
Labels: documentation, Drupal 7, UX

#160 Switch API form label from Account to Organization.
  modules/quant_api/src/Client/QuantClient.php
  modules/quant_api/src/Form/SettingsForm.php
  modules/quant_api/tests/src/Unit/QuantClientTest.php
Labels: Drupal 8 / 9 / 10, UX, task

#163 Add docs links for all tabs for easier onboarding.
  modules/quant_api/quant_api.admin.inc
  modules/quant_cron/quant_cron.admin.inc
  quant.admin.inc
Labels: documentation, Drupal 7, needs review, task

#173 Add hook_uninstall for all modules to remove variables.
  modules/quant_api/quant_api.info
  modules/quant_api/quant_api.install
  modules/quant_cron/quant_cron.install
  modules/quant_file/quant_file.install
  modules/quant_redirect/quant_redirect.install
  modules/quant_sitemap/quant_sitemap.install
  quant.install
Labels: bug, Drupal 7, needs review, DX

#172 Add clear queue button to seed form and align buttons.
  quant.admin.inc
  quant.module
Labels: enhancement, needs review, UX

#171 Add basic token timeout validation.
  quant.admin.inc
Labels: Drupal 7, needs review, UX, task

#170 Add hook_help to all modules.
  modules/quant_api/quant_api.module
  modules/quant_cron/quant_cron.module
  modules/quant_file/quant_file.info
  modules/quant_file/quant_file.module
  modules/quant_redirect/quant_redirect.module
  modules/quant_scheduler/quant_scheduler.info
  modules/quant_scheduler/quant_scheduler.module
  modules/quant_sitemap/quant_sitemap.module
  quant.module
Labels: documentation, Drupal 7, needs review, UX

#169 Updated to get rid of erroneous "Strict token mismatch" logs.
  quant.module
Labels: bug, Drupal 7, needs review

#165 Minor menu adjustment to match D9 and have better onboarding UX.
  modules/quant_api/quant_api.module
  modules/quant_cron/quant_cron.module
  quant.module
Labels: Drupal 7, needs review, UX, task

#164 Basic checks for hostname field.
  quant.admin.inc
Labels: Drupal 7, needs review, UX, task

#154 Resolve internal redirect failures when using storage_api.
  modules/quant_api/quant_api.module
  quant.admin.inc
  quant.module
Labels: enhancement, Drupal 7
