Repository quantcdn/drupal, pull requests merged in 2023-02, with the labels that each got.

#117 [ISSUE-116] Show Views options only if Views is enabled.
  modules/quant_cron/quant_cron.admin.inc
  quant.admin.inc
Labels: bug, Drupal 7, needs review, UX

#115 [ISSUE-114] Update drush command messaging for consistency.
  quant.drush.inc
  quant.module
Labels: documentation, Drupal 7, needs review, DX

#111 [ISSUE-109] Handle edge case when entity URI is empty.
  quant.module
Labels: bug, Drupal 7, needs review

#108 [ISSUE-107] Fix typos including rel canonical bug.
  modules/quant_api/quant_api.module
  modules/quant_cron/quant_cron.admin.inc
  modules/quant_cron/quant_cron.module
  modules/quant_file/quant_file.info
  modules/quant_redirect/quant_redirect.install
  modules/quant_redirect/quant_redirect.module
  quant.admin.inc
  quant.api.inc
  quant.install
  quant.module
  quant.renderer.inc
Labels: bug, Drupal 7, needs review

#106 [ISSUE-105] Switch to American English.
  modules/quant_api/quant_api.admin.inc
  modules/quant_redirect/quant_redirect.module
  quant.module
Labels: Drupal 7, needs review, task

#104 [ISSUE-103] Add quant module as dependency for quant_api module.
  modules/quant_api/quant_api.info
Labels: bug, Drupal 7, needs review

#97 Restored quant_cron submodule functionality.
  modules/quant_api/quant_api.admin.inc
  modules/quant_api/quant_api.module
  modules/quant_cron/quant_cron.module
  quant.module
Labels: bug, Drupal 7

#41 Fix queue_info override in drush runner.
  quant.drush.inc
  quant.module
Labels: bug, Drupal 7, needs review

#102 Add Facet values limit control
  modules/quant_search/js/quant-search.js
  modules/quant_search/quant_search.install
  modules/quant_search/src/Form/QuantSearchPageForm.php
Labels: enhancement, Drupal 8 / 9 / 10

#129 [ISSUE-128] Handle edge case when file URL is empty.
  modules/quant_file/quant_file.module
Labels: bug, Drupal 7, needs review

#127 [ISSUE-126] Update verbose logging so it's not empty.
  modules/quant_api/quant_api.module
Labels: bug, Drupal 7, needs review

#123 [ISSUE-122] Cast redirect status to int to fix redirect seeding.
  modules/quant_redirect/quant_redirect.module
Labels: bug, Drupal 7, needs review

#121 [ISSUE-120] Check site_404 before seeding _quant404.
  quant.module
Labels: bug, Drupal 7, needs review

#119 [ISSUE-118] Fix strpos error handling.
  modules/quant_api/quant_api.module
Labels: bug, Drupal 7, needs review

#133 [ISSUE-132] Cast redirect status to int to fix redirect handling.
  modules/quant_redirect/quant_redirect.module
Labels: bug, Drupal 7

#125 [ISSUE-124] Use Quant's base URL for sitemaps to fix seeding.
  modules/quant_sitemap/quant_sitemap.module
Labels: bug, Drupal 7

#92 Quant Cron: Skip node_modules when syncing theme assets.
  modules/quant_cron/quant_cron.module
Labels: enhancement, Drupal 8 / 9 / 10, needs work

#93 Strip DRUPAL_ROOT if already in the file path.
  src/Plugin/QueueItem/FileItem.php
Labels: bug, Drupal 8 / 9 / 10, needs review

#137 [ISSUE-100] Handle case when redirect source path changes.
  modules/quant_search/src/Form/QuantSearchPageForm.php
  src/Seed.php
Labels: bug, Drupal 8 / 9 / 10, needs review
